# Request data for uniboard_communication service
# String with the requested function
string function
int32 priority
# Pass data as a list of arguements
string data
# A timestamp for debugging purposes and it never hurts to timestamp messages
time timestamp

---
# Response data for uniboard_communcation service
# Returns true for success false for failure
bool status
# Any response string from called function
string response
# Any response data from called function
string data
