/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.4.1.213 */
/* Module Version: 6.4 */
/* /usr/local/diamond/3.4_x64/ispfpga/bin/lin64/scuba -w -bus_exp 7 -bb -arch xo2c00 -type bram -wp 10 -rp 0011 -data_width 17 -num_rows 256 -rdata_width 17 -read_reg1 outreg -gsr DISABLED -reset_rel async -memformat bin -cascade -1 -n pmi_ram_dpXbnonesadr17825617825611aca37d -pmi -lang verilog  */
/* Sun Jan 10 00:10:46 2016 */


`timescale 1 ns / 1 ps
module pmi_ram_dpXbnonesadr17825617825611aca37d (WrAddress, RdAddress, 
    Data, WE, RdClock, RdClockEn, Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] WrAddress;
    input wire [7:0] RdAddress;
    input wire [16:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [16:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0 (.DI17(scuba_vlo), 
        .DI16(Data[16]), .DI15(Data[15]), .DI14(Data[14]), .DI13(Data[13]), 
        .DI12(Data[12]), .DI11(Data[11]), .DI10(Data[10]), .DI9(Data[9]), 
        .DI8(Data[8]), .DI7(Data[7]), .DI6(Data[6]), .DI5(Data[5]), .DI4(Data[4]), 
        .DI3(Data[3]), .DI2(Data[2]), .DI1(Data[1]), .DI0(Data[0]), .ADW8(scuba_vlo), 
        .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), 
        .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), 
        .BE1(scuba_vhi), .BE0(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW2(scuba_vlo), .CSW1(scuba_vlo), .CSW0(WE), .ADR12(scuba_vlo), 
        .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), .ADR9(RdAddress[5]), 
        .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), .ADR5(RdAddress[1]), 
        .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), .ADR1(scuba_vlo), 
        .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), .CLKR(RdClock), 
        .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), .RST(Reset), 
        .DO17(Q[8]), .DO16(Q[7]), .DO15(Q[6]), .DO14(Q[5]), .DO13(Q[4]), 
        .DO12(Q[3]), .DO11(Q[2]), .DO10(Q[1]), .DO9(Q[0]), .DO8(), .DO7(Q[16]), 
        .DO6(Q[15]), .DO5(Q[14]), .DO4(Q[13]), .DO3(Q[12]), .DO2(Q[11]), 
        .DO1(Q[10]), .DO0(Q[9]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr17825617825611aca37d__PMIP__256__17__17B" */
             /* synthesis MEM_INIT_FILE="" */;



    // exemplar begin
    // exemplar attribute pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0 MEM_LPC_FILE pmi_ram_dpXbnonesadr17825617825611aca37d__PMIP__256__17__17B
    // exemplar attribute pmi_ram_dpXbnonesadr17825617825611aca37d_0_0_0 MEM_INIT_FILE 
    // exemplar end

endmodule
